is_debug: false
postgres:
  host: 0.0.0.0
  port: 5432
  user: postgres
  pass: example
  db: postgres
secret: verymegapupersupersecretpassword1231241245124124
patterns:
  user: "[a-zA-Z0-9_]+"
  password: "[a-zA-Z0-9а-яА-Я]+"